[project]
name = "taxmapp-switzerland"
version = "1.1.2"
description = "Compare taxes in Switzerland"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "altair==5.3.0",
    "geopandas>=1.0.1",
    "polars>=1.17.1",
    "streamlit>=1.40.1",
    "xlsx2csv>=0.8.4",
]
